# Selecting Columns

## 1. Selection with brackets:

In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv("titanic.csv")

In [3]:
type(titanic)

pandas.core.frame.DataFrame

In [4]:
titanic["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ...
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [5]:
type(titanic["age"])

pandas.core.series.Series

In [6]:
titanic[["age", "sex"]]

      age     sex
0    22.0    male
1    38.0  female
2    26.0  female
3    35.0  female
4    35.0    male
5     NaN    male
6    54.0    male
7     2.0    male
8    27.0  female
9    14.0  female
10    4.0  female
11   58.0  female
12   20.0    male
13   39.0    male
14   14.0  female
15   55.0  female
16    2.0    male
17    NaN    male
18   31.0  female
19    NaN  female
20   35.0    male
21   34.0    male
22   15.0  female
23   28.0    male
24    8.0  female
25   38.0  female
26    NaN    male
27   19.0    male
28    NaN  female
29    NaN    male
..    ...     ...
861  21.0    male
862  48.0  female
863   NaN  female
864  24.0    male
865  42.0  female
866  27.0  female
867  31.0    male
868   NaN    male
869   4.0    male
870  26.0    male
871  47.0  female
872  33.0    male
873  47.0    male
874  28.0  female
875  15.0  female
876  20.0    male
877  19.0    male
878   NaN    male
879  56.0  female
880  25.0  female
881  33.0    male
882  22.0  female
883  28.0    male
884  25.0    male
885  39.0  female
886  27.0    male
887  19.0  female
888   NaN  female
889  26.0    male
890  32.0    male

[891 rows x 2 columns]

In [7]:
type(titanic[["sex", "age"]])

pandas.core.frame.DataFrame

In [8]:
titanic[["age", "sex", "fare"]]

      age     sex      fare
0    22.0    male    7.2500
1    38.0  female   71.2833
2    26.0  female    7.9250
3    35.0  female   53.1000
4    35.0    male    8.0500
5     NaN    male    8.4583
6    54.0    male   51.8625
7     2.0    male   21.0750
8    27.0  female   11.1333
9    14.0  female   30.0708
10    4.0  female   16.7000
11   58.0  female   26.5500
12   20.0    male    8.0500
13   39.0    male   31.2750
14   14.0  female    7.8542
15   55.0  female   16.0000
16    2.0    male   29.1250
17    NaN    male   13.0000
18   31.0  female   18.0000
19    NaN  female    7.2250
20   35.0    male   26.0000
21   34.0    male   13.0000
22   15.0  female    8.0292
23   28.0    male   35.5000
24    8.0  female   21.0750
25   38.0  female   31.3875
26    NaN    male    7.2250
27   19.0    male  263.0000
28    NaN  female    7.8792
29    NaN    male    7.8958
..    ...     ...       ...
861  21.0    male   11.5000
862  48.0  female   25.9292
863   NaN  female   69.5500
864  24.0    male   13.0000
865  42.0  female   13.0000
866  27.0  female   13.8583
867  31.0    male   50.4958
868   NaN    male    9.5000
869   4.0    male   11.1333
870  26.0    male    7.8958
871  47.0  female   52.5542
872  33.0    male    5.0000
873  47.0    male    9.0000
874  28.0  female   24.0000
875  15.0  female    7.2250
876  20.0    male    9.8458
877  19.0    male    7.8958
878   NaN    male    7.8958
879  56.0  female   83.1583
880  25.0  female   26.0000
881  33.0    male    7.8958
882  22.0  female   10.5167
883  28.0    male   10.5000
884  25.0    male    7.0500
885  39.0  female   29.1250
886  27.0    male   13.0000
887  19.0  female   30.0000
888   NaN  female   23.4500
889  26.0    male   30.0000
890  32.0    male    7.7500

[891 rows x 3 columns]

## 2. Selection with the dot notation:

In [9]:
titanic.age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
5       NaN
6      54.0
7       2.0
8      27.0
9      14.0
10      4.0
11     58.0
12     20.0
13     39.0
14     14.0
15     55.0
16      2.0
17      NaN
18     31.0
19      NaN
20     35.0
21     34.0
22     15.0
23     28.0
24      8.0
25     38.0
26      NaN
27     19.0
28      NaN
29      NaN
       ...
861    21.0
862    48.0
863     NaN
864    24.0
865    42.0
866    27.0
867    31.0
868     NaN
869     4.0
870    26.0
871    47.0
872    33.0
873    47.0
874    28.0
875    15.0
876    20.0
877    19.0
878     NaN
879    56.0
880    25.0
881    33.0
882    22.0
883    28.0
884    25.0
885    39.0
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [10]:
titanic.age.equals(titanic["age"])

True

In [11]:
titanic.embarked

0      S
1      C
2      S
3      S
4      S
5      Q
6      S
7      S
8      S
9      C
10     S
11     S
12     S
13     S
14     S
15     S
16     Q
17     S
18     S
19     C
20     S
21     S
22     Q
23     S
24     S
25     S
26     C
27     S
28     Q
29     S
      ..
861    S
862    S
863    S
864    S
865    S
866    C
867    S
868    S
869    S
870    S
871    S
872    S
873    S
874    C
875    C
876    S
877    S
878    S
879    C
880    S
881    S
882    S
883    S
884    S
885    Q
886    S
887    S
888    S
889    C
890    Q
Name: embarked, Length: 891, dtype: object

## 3. Selection with Indexes and iloc :

In [12]:
summer = pd.read_csv("summer.csv", index_col="Athlete")

In [13]:
summer

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...
"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [14]:
summer.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31165 entries, HAJOS, Alfred to LIDBERG, Jimmy
Data columns (total 8 columns):
Year          31165 non-null int64
City          31165 non-null object
Sport         31165 non-null object
Discipline    31165 non-null object
Country       31161 non-null object
Gender        31165 non-null object
Event         31165 non-null object
Medal         31165 non-null object
dtypes: int64(1), object(7)
memory usage: 2.1+ MB

In [15]:
summer.iloc[0]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  HUN
Gender                   Men
Event         100M Freestyle
Medal                   Gold
Name: HAJOS, Alfred, dtype: object

In [16]:
type(summer.iloc)

pandas.core.indexing._iLocIndexer

In [17]:
type(summer.iloc[0])

pandas.core.series.Series

In [18]:
summer.iloc[1]

Year                    1896
City                  Athens
Sport               Aquatics
Discipline          Swimming
Country                  AUT
Gender                   Men
Event         100M Freestyle
Medal                 Silver
Name: HERSCHMANN, Otto, dtype: object

In [19]:
summer.iloc[-1]

Year                         2012
City                       London
Sport                   Wrestling
Discipline    Wrestling Freestyle
Country                       SWE
Gender                        Men
Event                    Wg 96 KG
Medal                      Bronze
Name: LIDBERG, Jimmy, dtype: object

In [20]:
summer.iloc[[1,2,3]]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold

In [21]:
summer.iloc[1:4]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold

In [22]:
summer.iloc[:5]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [23]:
summer.iloc[0:5]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

In [24]:
summer.iloc[-5:]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [25]:
summer.iloc[:]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...
"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [26]:
summer.iloc[[4, 49, 666]]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"KONSTANTINIDIS, Aristidis",1896,Athens,Cycling,Cycling Road,GRE,Men,Individual Road Race,Gold
"HOFFMANN, Georg",1904,St Louis,Aquatics,Diving,GER,Men,10M Platform,Silver

In [27]:
summer.head(10)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold

In [29]:
summer.iloc[0, 4]

'HUN'

In [30]:
summer.iloc[0, :3]

Year         1896
City       Athens
Sport    Aquatics
Name: HAJOS, Alfred, dtype: object

In [31]:
summer.iloc[0, [2, 3,4,5]]

Sport         Aquatics
Discipline    Swimming
Country            HUN
Gender             Men
Name: HAJOS, Alfred, dtype: object

## Selecting Columns with Iloc[]

In [34]:
summer.iloc[:, 4]

Athlete
HAJOS, Alfred                        HUN
HERSCHMANN, Otto                     AUT
DRIVAS, Dimitrios                    GRE
MALOKINIS, Ioannis                   GRE
CHASAPIS, Spiridon                   GRE
CHOROPHAS, Efstathios                GRE
HAJOS, Alfred                        HUN
ANDREOU, Joannis                     GRE
CHOROPHAS, Efstathios                GRE
NEUMANN, Paul                        AUT
PEPANOS, Antonios                    GRE
LANE, Francis                        USA
SZOKOLYI, Alajos                     HUN
BURKE, Thomas                        USA
HOFMANN, Fritz                       GER
CURTIS, Thomas                       USA
GOULDING, Grantley                   GBR
LERMUSIAUX, Albin                    FRA
FLACK, Edwin                         AUS
BLAKE, Arthur                        USA
GMELIN, Charles                      GBR
BURKE, Thomas                        USA
JAMISON, Herbert                     USA
GOLEMIS, Dimitrios                   GRE
FLACK, Edwin                         AUS
DANI, Nandor                         HUN
VERSIS, Sotirios                     GRE
GARRETT, Robert                      USA
PARASKEVOPOULOS, Panagiotis          GRE
CLARK, Ellery                        USA
                                    ...
GAZYUMOV, Khetag                     AZE
GOGSHELIDZE, George                  GEO
LOPEZ NUNEZ, Mijain                  CUB
NABI, Heiki                          EST
EUREN, Johan                         SWE
KAYAALP, Riza                        TUR
SORYAN REIHANPOUR, Hamid Mohammad    IRI
BAYRAMOV, Rovshan                    AZE
MODOS, Peter                         HUN
SEMENOV, Mingiyan                    RUS
NOROOZI, Omid Haji                   IRI
LASHKHI, Revaz                       GEO
KURAMAGOMEDOV, Zaur                  RUS
MATSUMOTO, Ryutaro                   JPN
KIM, Hyeonwoo                        KOR
LORINCZ, Tamas                       HUN
GUENOT, Steeve                       FRA
TSKHADAIA, Manuchar                  GEO
VLASOV, Roman                        RUS
JULFALAKYAN, Arsen                   ARM
AHMADOV, Emin                        AZE
KAZAKEVIC, Aleksandr                 LTU
KHUGAEV, Alan                        RUS
EBRAHIM, Karam Mohamed Gaber         EGY
GAJIYEV, Danyal                      KAZ
JANIKOWSKI, Damian                   POL
REZAEI, Ghasem Gholamreza            IRI
TOTROV, Rustam                       RUS
ALEKSANYAN, Artur                    ARM
LIDBERG, Jimmy                       SWE
Name: Country, Length: 31165, dtype: object

In [35]:
summer.iloc[:, 4].equals(summer["Country"])

True

# Label Based Indexing:

## 1. Selecting Rows with loc[]:

In [39]:
summer.loc["HAJOS, Alfred"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold

In [40]:
summer.loc["PHELPS, Michael"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Butterfly,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Freestyle,Bronze
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,200M Individual Medley,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,400M Individual Medley,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X100M Freestyle Relay,Bronze
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X100M Medley Relay,Gold
"PHELPS, Michael",2004,Athens,Aquatics,Swimming,USA,Men,4X200M Freestyle Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Butterfly,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Freestyle,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,200M Individual Medley,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,400M Individual Medley,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X100M Freestyle Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X100M Medley Relay,Gold
"PHELPS, Michael",2008,Beijing,Aquatics,Swimming,USA,Men,4X200M Freestyle Relay,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,100M Butterfly,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,200M Butterfly,Silver
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,200M Medley,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X100M Freestyle,Silver
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X100M Medley,Gold
"PHELPS, Michael",2012,London,Aquatics,Swimming,USA,Men,4X200M Freestyle,Gold

## 2. Slicing Rows and Columns with loc[]:

In [43]:
summer.loc["PHELPS, Michael", ["Medal", "Event"]]

                  Medal                   Event
Athlete
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael  Bronze          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael  Bronze  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael    Gold          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael    Gold  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael  Silver          200M Butterfly
PHELPS, Michael    Gold             200M Medley
PHELPS, Michael  Silver        4X100M Freestyle
PHELPS, Michael    Gold           4X100M Medley
PHELPS, Michael    Gold        4X200M Freestyle

In [46]:
summer.loc[["PHELPS, Michael", "HOFMANN, Fritz"], ["Medal", "Event"]]

                  Medal                   Event
Athlete
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael  Bronze          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael  Bronze  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael    Gold          200M Butterfly
PHELPS, Michael    Gold          200M Freestyle
PHELPS, Michael    Gold  200M Individual Medley
PHELPS, Michael    Gold  400M Individual Medley
PHELPS, Michael    Gold  4X100M Freestyle Relay
PHELPS, Michael    Gold     4X100M Medley Relay
PHELPS, Michael    Gold  4X200M Freestyle Relay
PHELPS, Michael    Gold          100M Butterfly
PHELPS, Michael  Silver          200M Butterfly
PHELPS, Michael    Gold             200M Medley
PHELPS, Michael  Silver        4X100M Freestyle
PHELPS, Michael    Gold           4X100M Medley
PHELPS, Michael    Gold        4X200M Freestyle
HOFMANN, Fritz   Silver                    100M
HOFMANN, Fritz   Bronze           Rope Climbing
HOFMANN, Fritz     Gold    Team, Horizontal Bar
HOFMANN, Fritz     Gold     Team, Parallel Bars

In [47]:
summer.loc[:"CHASAPIS, Spiridon"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver

##### Error when slicing with non unique label

In [54]:
summer.loc[:"PHELPS, Michael"]

KeyError: "Cannot get right slice bound for non-unique label: 'PHELPS, Michael'"

In [49]:
summer.head(20)

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver

In [50]:
summer.loc["DRIVAS, Dimitrios":"BLAKE, Arthur"]

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver

#### Error in case we specify non-existent column

In [52]:
 summer.loc["PHELPS, Michael": "Kind"]

KeyError: "Cannot get left slice bound for non-unique label: 'PHELPS, Michael'"

# 3 Indexing with Reindex

In [66]:
summer

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...
"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

In [89]:
summer.loc[[0, 5], ["Medal"]]

KeyError: "None of [Int64Index([0, 5], dtype='int64', name='Athlete')] are in the [index]"

In [92]:
summer.reindex(index=ex=, columns=)

ValueError: cannot reindex from a duplicate axis

## selecting a column as an index

In [94]:
summer = pd.read_csv("summer.csv", index_col="Athlete")

In [95]:
summer

,Year,City,Sport,Discipline,Country,Gender,Event,Medal
Athlete,,,,,,,,
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,100M Freestyle,Gold
"HERSCHMANN, Otto",1896,Athens,Aquatics,Swimming,AUT,Men,100M Freestyle,Silver
"DRIVAS, Dimitrios",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Bronze
"MALOKINIS, Ioannis",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Gold
"CHASAPIS, Spiridon",1896,Athens,Aquatics,Swimming,GRE,Men,100M Freestyle For Sailors,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Bronze
"HAJOS, Alfred",1896,Athens,Aquatics,Swimming,HUN,Men,1200M Freestyle,Gold
"ANDREOU, Joannis",1896,Athens,Aquatics,Swimming,GRE,Men,1200M Freestyle,Silver
"CHOROPHAS, Efstathios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Bronze
"NEUMANN, Paul",1896,Athens,Aquatics,Swimming,AUT,Men,400M Freestyle,Gold
"PEPANOS, Antonios",1896,Athens,Aquatics,Swimming,GRE,Men,400M Freestyle,Silver
"LANE, Francis",1896,Athens,Athletics,Athletics,USA,Men,100M,Bronze
"SZOKOLYI, Alajos",1896,Athens,Athletics,Athletics,HUN,Men,100M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,100M,Gold
"HOFMANN, Fritz",1896,Athens,Athletics,Athletics,GER,Men,100M,Silver
"CURTIS, Thomas",1896,Athens,Athletics,Athletics,USA,Men,110M Hurdles,Gold
"GOULDING, Grantley",1896,Athens,Athletics,Athletics,GBR,Men,110M Hurdles,Silver
"LERMUSIAUX, Albin",1896,Athens,Athletics,Athletics,FRA,Men,1500M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,1500M,Gold
"BLAKE, Arthur",1896,Athens,Athletics,Athletics,USA,Men,1500M,Silver
"GMELIN, Charles",1896,Athens,Athletics,Athletics,GBR,Men,400M,Bronze
"BURKE, Thomas",1896,Athens,Athletics,Athletics,USA,Men,400M,Gold
"JAMISON, Herbert",1896,Athens,Athletics,Athletics,USA,Men,400M,Silver
"GOLEMIS, Dimitrios",1896,Athens,Athletics,Athletics,GRE,Men,800M,Bronze
"FLACK, Edwin",1896,Athens,Athletics,Athletics,AUS,Men,800M,Gold
"DANI, Nandor",1896,Athens,Athletics,Athletics,HUN,Men,800M,Silver
"VERSIS, Sotirios",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Bronze
"GARRETT, Robert",1896,Athens,Athletics,Athletics,USA,Men,Discus Throw,Gold
"PARASKEVOPOULOS, Panagiotis",1896,Athens,Athletics,Athletics,GRE,Men,Discus Throw,Silver
"CLARK, Ellery",1896,Athens,Athletics,Athletics,USA,Men,High Jump,Gold
...,...,...,...,...,...,...,...,...
"GAZYUMOV, Khetag",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wf 96 KG,Bronze
"GOGSHELIDZE, George",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wf 96 KG,Bronze
"LOPEZ NUNEZ, Mijain",2012,London,Wrestling,Wrestling Freestyle,CUB,Men,Wg 120 KG,Gold
"NABI, Heiki",2012,London,Wrestling,Wrestling Freestyle,EST,Men,Wg 120 KG,Silver
"EUREN, Johan",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 120 KG,Bronze
"KAYAALP, Riza",2012,London,Wrestling,Wrestling Freestyle,TUR,Men,Wg 120 KG,Bronze
"SORYAN REIHANPOUR, Hamid Mohammad",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 55 KG,Gold
"BAYRAMOV, Rovshan",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 55 KG,Silver
"MODOS, Peter",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 55 KG,Bronze
"SEMENOV, Mingiyan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 55 KG,Bronze
"NOROOZI, Omid Haji",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 60 KG,Gold
"LASHKHI, Revaz",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 60 KG,Silver
"KURAMAGOMEDOV, Zaur",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 60 KG,Bronze
"MATSUMOTO, Ryutaro",2012,London,Wrestling,Wrestling Freestyle,JPN,Men,Wg 60 KG,Bronze
"KIM, Hyeonwoo",2012,London,Wrestling,Wrestling Freestyle,KOR,Men,Wg 66 KG,Gold
"LORINCZ, Tamas",2012,London,Wrestling,Wrestling Freestyle,HUN,Men,Wg 66 KG,Silver
"GUENOT, Steeve",2012,London,Wrestling,Wrestling Freestyle,FRA,Men,Wg 66 KG,Bronze
"TSKHADAIA, Manuchar",2012,London,Wrestling,Wrestling Freestyle,GEO,Men,Wg 66 KG,Bronze
"VLASOV, Roman",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 74 KG,Gold
"JULFALAKYAN, Arsen",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 74 KG,Silver
"AHMADOV, Emin",2012,London,Wrestling,Wrestling Freestyle,AZE,Men,Wg 74 KG,Bronze
"KAZAKEVIC, Aleksandr",2012,London,Wrestling,Wrestling Freestyle,LTU,Men,Wg 74 KG,Bronze
"KHUGAEV, Alan",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 84 KG,Gold
"EBRAHIM, Karam Mohamed Gaber",2012,London,Wrestling,Wrestling Freestyle,EGY,Men,Wg 84 KG,Silver
"GAJIYEV, Danyal",2012,London,Wrestling,Wrestling Freestyle,KAZ,Men,Wg 84 KG,Bronze
"JANIKOWSKI, Damian",2012,London,Wrestling,Wrestling Freestyle,POL,Men,Wg 84 KG,Bronze
"REZAEI, Ghasem Gholamreza",2012,London,Wrestling,Wrestling Freestyle,IRI,Men,Wg 96 KG,Gold
"TOTROV, Rustam",2012,London,Wrestling,Wrestling Freestyle,RUS,Men,Wg 96 KG,Silver
"ALEKSANYAN, Artur",2012,London,Wrestling,Wrestling Freestyle,ARM,Men,Wg 96 KG,Bronze
"LIDBERG, Jimmy",2012,London,Wrestling,Wrestling Freestyle,SWE,Men,Wg 96 KG,Bronze

### With reindex, we can reference non-existing columns, we'll get NaN values but no errors.
ex: Age
### Note: we always pass lists to colums and index params of reindex, even if we only pass one value

In [100]:
summer.reindex(columns=["Medal", "Age"])

                                    Medal  Age
Athlete
HAJOS, Alfred                        Gold  NaN
HERSCHMANN, Otto                   Silver  NaN
DRIVAS, Dimitrios                  Bronze  NaN
MALOKINIS, Ioannis                   Gold  NaN
CHASAPIS, Spiridon                 Silver  NaN
CHOROPHAS, Efstathios              Bronze  NaN
HAJOS, Alfred                        Gold  NaN
ANDREOU, Joannis                   Silver  NaN
CHOROPHAS, Efstathios              Bronze  NaN
NEUMANN, Paul                        Gold  NaN
PEPANOS, Antonios                  Silver  NaN
LANE, Francis                      Bronze  NaN
SZOKOLYI, Alajos                   Bronze  NaN
BURKE, Thomas                        Gold  NaN
HOFMANN, Fritz                     Silver  NaN
CURTIS, Thomas                       Gold  NaN
GOULDING, Grantley                 Silver  NaN
LERMUSIAUX, Albin                  Bronze  NaN
FLACK, Edwin                         Gold  NaN
BLAKE, Arthur                      Silver  NaN
GMELIN, Charles                    Bronze  NaN
BURKE, Thomas                        Gold  NaN
JAMISON, Herbert                   Silver  NaN
GOLEMIS, Dimitrios                 Bronze  NaN
FLACK, Edwin                         Gold  NaN
DANI, Nandor                       Silver  NaN
VERSIS, Sotirios                   Bronze  NaN
GARRETT, Robert                      Gold  NaN
PARASKEVOPOULOS, Panagiotis        Silver  NaN
CLARK, Ellery                        Gold  NaN
...                                   ...  ...
GAZYUMOV, Khetag                   Bronze  NaN
GOGSHELIDZE, George                Bronze  NaN
LOPEZ NUNEZ, Mijain                  Gold  NaN
NABI, Heiki                        Silver  NaN
EUREN, Johan                       Bronze  NaN
KAYAALP, Riza                      Bronze  NaN
SORYAN REIHANPOUR, Hamid Mohammad    Gold  NaN
BAYRAMOV, Rovshan                  Silver  NaN
MODOS, Peter                       Bronze  NaN
SEMENOV, Mingiyan                  Bronze  NaN
NOROOZI, Omid Haji                   Gold  NaN
LASHKHI, Revaz                     Silver  NaN
KURAMAGOMEDOV, Zaur                Bronze  NaN
MATSUMOTO, Ryutaro                 Bronze  NaN
KIM, Hyeonwoo                        Gold  NaN
LORINCZ, Tamas                     Silver  NaN
GUENOT, Steeve                     Bronze  NaN
TSKHADAIA, Manuchar                Bronze  NaN
VLASOV, Roman                        Gold  NaN
JULFALAKYAN, Arsen                 Silver  NaN
AHMADOV, Emin                      Bronze  NaN
KAZAKEVIC, Aleksandr               Bronze  NaN
KHUGAEV, Alan                        Gold  NaN
EBRAHIM, Karam Mohamed Gaber       Silver  NaN
GAJIYEV, Danyal                    Bronze  NaN
JANIKOWSKI, Damian                 Bronze  NaN
REZAEI, Ghasem Gholamreza            Gold  NaN
TOTROV, Rustam                     Silver  NaN
ALEKSANYAN, Artur                  Bronze  NaN
LIDBERG, Jimmy                     Bronze  NaN

[31165 rows x 2 columns]